"""
Django settings for new3 project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default):
    value = os.getenv(name)
    if not value:
        return default
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-5%mi_w9x5b+5(z9kw1fbew$sugno7+u=p%pi1$487b*uo2*#x$",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", ["127.0.0.1", "localhost"])

INSTALLED_APPS = [
    "django.contrib.admin", # admin 추가
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "blog",
]  #blog 회원관리 앱 추가


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
# asjdfhkjshdf
ROOT_URLCONF = "new3.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "new3.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / os.getenv("DJANGO_DB_NAME", "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [("ppt-assets", BASE_DIR / "ppt-renderer" / "assets")]
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "tmp" / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'blog.CustomUser'

# 이메일 백엔드 설정
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 이메일 서버 설정
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")  # Gmail SMTP 서버
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))  # SMTP 포트 (TLS)
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)  # TLS를 사용
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "autoppt3@gmail.com")  # 보내는 이메일 주소
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "fqhh wfyc rngk dxfp")  # Gmail 앱 비밀번호
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # 이메일 보내는 사람

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_FILENAME_MODEL = os.getenv("OPENAI_FILENAME_MODEL", "gpt-3.5-turbo-1106")
OPENAI_PRESENTATION_MODEL = os.getenv("OPENAI_PRESENTATION_MODEL", "gpt-4-turbo")
PPT_RENDER_BACKEND = os.getenv("PPT_RENDER_BACKEND", "pptxgenjs")
GOOGLE_CLIENT_SECRET_FILE = os.getenv(
    "GOOGLE_CLIENT_SECRET_FILE", str(BASE_DIR / "client_secret.json")
)
GOOGLE_SERVICE_ACCOUNT_FILE = os.getenv(
    "GOOGLE_SERVICE_ACCOUNT_FILE", str(BASE_DIR / "credentials.json")
)
GOOGLE_TOKEN_FILE = os.getenv("GOOGLE_TOKEN_FILE", str(BASE_DIR / "token.json"))
PPT_RENDERER_DIR = os.getenv("PPT_RENDERER_DIR", str(BASE_DIR / "ppt-renderer"))
PPT_RENDER_OUTPUT_DIR = os.getenv(
    "PPT_RENDER_OUTPUT_DIR", str(BASE_DIR / "tmp" / "rendered-presentations")
)
USER_TEMPLATE_STORAGE_DIR = os.getenv(
    "USER_TEMPLATE_STORAGE_DIR", str(BASE_DIR / "tmp" / "user-templates")
)

# 세션과 만료시 로그아웃
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 1800  # 30분
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
