# Generated by Django 5.1.6 on 2025-02-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='ppt_title',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
