# Generated by Django 5.1.6 on 2026-03-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_userhistory_ppt_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhistory",
            name="backend",
            field=models.CharField(
                choices=[("legacy-google", "Google Slides"), ("pptxgenjs", "PptxGenJS")],
                default="legacy-google",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="userhistory",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="userhistory",
            name="file_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="userhistory",
            name="status",
            field=models.CharField(
                choices=[("completed", "Completed"), ("failed", "Failed")],
                default="completed",
                max_length=32,
            ),
        ),
    ]
