# Generated by Django 5.1.6 on 2026-03-25 00:10

from django.db import migrations


def normalize_local_history_urls(apps, schema_editor):
    UserHistory = apps.get_model("blog", "UserHistory")
    UserHistory.objects.filter(
        backend="pptxgenjs",
        file_path__gt="",
    ).exclude(ppt_url="").update(ppt_url="")


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_userhistory_render_fields"),
    ]

    operations = [
        migrations.RunPython(normalize_local_history_urls, migrations.RunPython.noop),
    ]
