# Generated by Django 5.1.6 on 2026-03-26 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userhistory_result_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('renderer_key', models.CharField(choices=[('modern-a', 'Template 1'), ('modern-b', 'Template 2')], default='modern-a', max_length=32)),
                ('original_filename', models.CharField(max_length=255)),
                ('source_pptx_path', models.CharField(max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
