# Generated by Django 5.1.6 on 2026-03-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_usertemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.FileField(blank=True, upload_to='profile-images/'),
        ),
    ]
