# Generated by Django 5.1.6 on 2026-04-01

from django.db import migrations, models


def migrate_legacy_google_histories(apps, schema_editor):
    UserHistory = apps.get_model("blog", "UserHistory")

    for history in UserHistory.objects.filter(backend="legacy-google"):
        payload = dict(history.result_payload or {})
        payload["backend"] = "pptxgenjs"
        if payload.get("primary_action_label") == "Google Slides 열기":
            payload["primary_action_label"] = "다운로드"
        if isinstance(payload.get("download_url"), str) and payload["download_url"].startswith("http"):
            payload["download_url"] = ""

        history.backend = "pptxgenjs"
        history.result_payload = payload
        history.save(update_fields=["backend", "result_payload"])


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_customuser_profile_image"),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_google_histories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userhistory",
            name="backend",
            field=models.CharField(
                choices=[("pptxgenjs", "PptxGenJS")],
                default="pptxgenjs",
                max_length=32,
            ),
        ),
    ]
